# Generated by Django 3.1.4 on 2021-01-07 23:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('categories', models.CharField(choices=[('gears', 'Gears'), ('gaming', 'Gaming'), ('entertainment', 'Entertainment'), ('productreview', 'Product Review'), ('technology', 'Technology'), ('deals', 'Deals'), ('trending', 'Trending')], default='gears', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='blog_photos')),
                ('excerpts', models.CharField(max_length=150)),
                ('date', models.DateField(blank=True)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
